"""creating tables

Revision ID: 2b6ddb6c1fc1
Revises: 
Create Date: 2023-07-29 15:46:14.825515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6ddb6c1fc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('company_revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('organiser',
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.PrimaryKeyConstraint('organiser_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organiser_id'], ['organiser.organiser_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('booked_events',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('date_paid', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['organiser_id'], ['organiser.organiser_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('revenue',
    sa.Column('revenue_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('admin_share', sa.Float(), nullable=False),
    sa.Column('organiser_share', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('revenue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revenue')
    op.drop_table('payment')
    op.drop_table('booked_events')
    op.drop_table('events')
    op.drop_table('organiser')
    op.drop_table('customer')
    op.drop_table('company_revenue')
    op.drop_table('admin')
    # ### end Alembic commands ###
